export default {
  index: "Changesets란?",
  "intro-to-using-changesets": "Changesets 사용 시작하기",
  "detailed-explanation": "Changesets 상세 설명",
  "common-questions": "자주 묻는 질문",
  "adding-a-changeset": "Changeset 추가하기",
  "automating-changesets": "Changesets 자동화",
  "checking-for-changesets": "Changeset 확인 방법",
  "command-line-options": "커맨드 라인 옵션",
  "config-file-options": "설정 파일 옵션",
  decisions: "설계 결정",
  dictionary: "용어집",
  "fixed-packages": "고정 패키지",
  "linked-packages": "링크된 패키지",
  "modifying-changelog-format": "Changelog 포맷 수정",
  prereleases: "프리릴리스",
  "problems-publishing-in-monorepos": "모노레포 배포 문제",
  "snapshot-releases": "스냅샷 릴리스",
  "versioning-apps": "애플리케이션 및 비-npm 패키지 버전 관리",
  "experimental-options": "실험적 옵션",
};
